spring:
  application:
    name: instructionsCcaptureApplication
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: instructions-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev

app:
  topics:
    inbound: instructions.inbound
    outbound: instructions.outbound

logging:
  level:
    root: INFO
    com.example.instructions: INFO

server:
  port: 8080